---
# ensure plugdev group exists
- name: Add plugdev group
  group:
    name: "plugdev"
    state: present

# ensure user is part of plugdev
- name: Add User to plugdev Group
  user:
    name: "{{ ansible_user }}"
    groups: "plugdev"
    append: yes

# install Solaar
- name: Install Solaar
  pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ logitech_apps }}"
  become: true
  when: ansible_facts.os_family == "Archlinux"
